server:
  port: 8091
  tomcat:
    uri-encoding: UTF-8

spring:
  config:
    activate:
      on-profile: "test"

  output:
    ansi:
      enabled: always

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: membership
    password: membership

  sql:
    init:
      schema-locations: classpath:init-data/h2db/schema.sql
      #data-locations: classpath:init-data/h2db/data.sql
      username: membership
      password: membership
      mode: always
      encoding: UTF-8

  h2:
    console:
      enabled: true
      path: /h2-console

